//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentTypeToExtn
    {
        public string Template { get; set; }
        public string Extn { get; set; }
        public bool IsText { get; set; }
    }
}
