//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DefaultConnection : DbContext
    {
        public DefaultConnection()
            : base("name=DefaultConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContentTypeToExtn> ContentTypeToExtns { get; set; }
        public virtual DbSet<WebPage> WebPages { get; set; }
    
        public virtual ObjectResult<WebPage> p_WebPage_IU(string url, string draftFilespec, string filespec, Nullable<bool> needDownload)
        {
            var urlParameter = url != null ?
                new ObjectParameter("Url", url) :
                new ObjectParameter("Url", typeof(string));
    
            var draftFilespecParameter = draftFilespec != null ?
                new ObjectParameter("DraftFilespec", draftFilespec) :
                new ObjectParameter("DraftFilespec", typeof(string));
    
            var filespecParameter = filespec != null ?
                new ObjectParameter("Filespec", filespec) :
                new ObjectParameter("Filespec", typeof(string));
    
            var needDownloadParameter = needDownload.HasValue ?
                new ObjectParameter("NeedDownload", needDownload) :
                new ObjectParameter("NeedDownload", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WebPage>("p_WebPage_IU", urlParameter, draftFilespecParameter, filespecParameter, needDownloadParameter);
        }
    
        public virtual ObjectResult<WebPage> p_WebPage_IU(string url, string draftFilespec, string filespec, Nullable<bool> needDownload, MergeOption mergeOption)
        {
            var urlParameter = url != null ?
                new ObjectParameter("Url", url) :
                new ObjectParameter("Url", typeof(string));
    
            var draftFilespecParameter = draftFilespec != null ?
                new ObjectParameter("DraftFilespec", draftFilespec) :
                new ObjectParameter("DraftFilespec", typeof(string));
    
            var filespecParameter = filespec != null ?
                new ObjectParameter("Filespec", filespec) :
                new ObjectParameter("Filespec", typeof(string));
    
            var needDownloadParameter = needDownload.HasValue ?
                new ObjectParameter("NeedDownload", needDownload) :
                new ObjectParameter("NeedDownload", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WebPage>("p_WebPage_IU", mergeOption, urlParameter, draftFilespecParameter, filespecParameter, needDownloadParameter);
        }
    }
}
