//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA4
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebPage()
        {
            this.SuppliesTo = new HashSet<WebPage>();
            this.SuppliedBy = new HashSet<WebPage>();
        }
    
        public int PageId { get; set; }
        public Nullable<int> HostId { get; set; }
        public string Url { get; set; }
        public string DraftFilespec { get; set; }
        public string Filespec { get; set; }
        public Nullable<bool> NeedDownload { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebPage> SuppliesTo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebPage> SuppliedBy { get; set; }
    }
}
